name: swe-bench
dependencies:
  - python=3.9
  - pip
  - pip:
    - beautifulsoup4
    - chardet
    - ghapi
    - GitPython
    - python-dotenv
    - requests
    - rich
    - transformers>=4.34.0
  - conda-forge::gh
